export const DATA_FORM = [
	{
		key: "userId",
		label: "Mã nhân viên",
		tag: "input",
		dataType: "text",
		sort_order: 1,
	},
	{
		key: "name",
		label: "Tên nhân viên",
		tag: "p",
		dataType: "text",
		sort_order: 2,
	},
	{
		key: "soNgayNghi",
		label: "Số ngày nghỉ",
		tag: "input",
		dataType: "number",
		sort_order: 3,
	},
	{
		key: "ngayBatDau",
		label: "Ngày bắt đầu",
		tag: "input",
		dataType: "date",
		sort_order: 6,
	},
	{
		key: "ngayKetThuc",
		label: "Ngày kết thúc",
		tag: "input",
		dataType: "date",
		sort_order: 5,
	},
	{
		key: "lyDo",
		label: "Lý do",
		tag: "input",
		dataType: "text",
		sort_order: 4,
	},
	{
		key: "taiLieuDinhKem",
		label: "Tài liệu",
		tag: "input",
		dataType: "file",
		sort_order: 7,
	},
];
