export const DATA_FORM = [
	{
		key: "userid",
		label: "Mã nhân viên",
		tag: "input",
		dataType: "text",
		sort_order: 1,
	},
	{
		key: "name",
		label: "Tên nhân viên",
		tag: "p",
		dataType: "text",
		sort_order: 2,
	},
	{
		key: "songaynghi",
		label: "Số ngày nghỉ",
		tag: "input",
		dataType: "text",
		sort_order: 3,
	},
	{
		key: "ngaybatdau",
		label: "Ngày bắt đầu",
		tag: "input",
		dataType: "date",
		sort_order: 6,
	},
	{
		key: "ngayketthuc",
		label: "Ngày kết thúc",
		tag: "input",
		dataType: "date",
		sort_order: 5,
	},
	{
		key: "lydo",
		label: "Lý do",
		tag: "input",
		dataType: "text",
		sort_order: 4,
	},
	{
		key: "tailieudinhkem",
		label: "Tài liệu",
		tag: "input",
		dataType: "file",
		sort_order: 7,
	},
];
